#Andrew Samuels - CPSC 3600 Project 1
#Makefile to compile the appropriate .c files
all: caseInverter yeller checker

caseInverter: caseInverter.c
	gcc -o caseInverter caseInverter.c

yeller: yeller.c
	gcc -o yeller yeller.c

checker: checker.c
	gcc -o checker checker.c
