#Andrew Samuels - CPSC 3600 Project 1
#Makefile to compile the appropriate .c files
all: chopper ahsoka starLord 

chopper : chopper.c
	gcc -o  chopper chopper.c

ahsoka: ahsoka.c
	gcc -o  ahsoka ahsoka.c

starLord: starLord.c
	gcc -o  starLord starLord.c
clean:
	rm -rf starLord chopper ahsoka
