#Andrew Samuels - CPSC 3600 Project 1
#Makefile to compile the appropriate .c files
all: caseConverter bellower frank

caseConverter: caseConverter.c
	gcc -o caseConverter caseConverter.c

bellower: bellower.c
	gcc -o bellower bellower.c

frank: frank.c
	gcc -o frank frank.c

